version: '3.4'

services:
  hoteldb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  hotel.api:
    image: ${DOCKER_REGISTRY-}hotelapi
    build:
      context: .
      dockerfile: Services/Hotel/Hotel.API/Dockerfile
      
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend: 
    driver: bridge

