version: '3.4'

services:
  hoteldb:
    image: postgres

  authdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  hotel.api:
    image: ${DOCKER_REGISTRY-}hotelapi
    build:
      context: .
      dockerfile: Services/Hotel/Hotel.API/Dockerfile
      
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  accountapi:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Authentication/AccountApi/Dockerfile

  reservation.api:
    image: ${DOCKER_REGISTRY-}reservationapi
    build:
      context: .
      dockerfile: Services/Reservation/Reservation.API/Dockerfile

volumes:
  postgres_hoteldb_data:
  postgres_authdb_data:
  pgadmin_data:

#networks:
#  backend: 
#    driver: bridge



