version: '3.4'

services:
  hoteldb:
    container_name: hoteldb
    environment:
      - POSTGRES_USER=Mohamed
      - POSTGRES_PASSWORD=admin2023
      - POSTGRES_DB=HotelDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_hoteldb_data:/var/lib/postgresql/data/
    #networks:
    #  - backend

  authdb:
    container_name: authdb
    environment:
      - POSTGRES_USER=Mohamed
      - POSTGRES_PASSWORD=admin2023
      - POSTGRES_DB=AuthDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_authdb_data:/var/lib/postgresql/data/
    #networks:
    #  - backend

  paymentdb:
    container_name: paymentdb
    environment:
      - POSTGRES_USER=Mohamed
      - POSTGRES_PASSWORD=admin2023
      - POSTGRES_DB=AuthDb
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_paymentdb_data:/var/lib/postgresql/data/
    #networks:
    #  - backend

  reservationdb:
    container_name: reservationdb
    environment:
      - POSTGRES_USER=Mohamed
      - POSTGRES_PASSWORD=admin2023
      - POSTGRES_DB=AuthDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_reservationdb_data:/var/lib/postgresql/data/
    #networks:
    #  - backend

  pgadmin:
    container_name: pgadmin_HRS
    environment:
      - PGADMIN_DEFAULT_EMAIL=Mohamed@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin2023
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    #networks:
    #  - backend

  hotel.api:
    container_name: hotel.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DbSettings__HotelDbConString=Host=hoteldb;Port=5432;Database=HotelDb;Username=Mohamed;Password=admin2023;"
    restart: always
    depends_on:
      - hoteldb
    #ports:
    #  - "8000:80"
    #networks:
    #  - backend

  apigateway:
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "5000:80"
    #networks:
    #  - backend


  accountapi:
    container_name: accountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuthDbSettings__AuthDbConString=Host=authdb;Port=5432;Database=AuthDb;Username=Mohamed;Password=admin2023;"
    restart: always
    depends_on: 
      - authdb
    #ports:
    #  - "80"
    #networks:
    #  - backend

  reservation.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DbSettings__ReservationDbConString=Host=reservationdb;Port=5432;Database=ReservationDb;Username=Mohamed;Password=admin2023;"
    restart: always
    depends_on:
      - reservationdb

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DbSettings__PaymentDbConString=Host=paymentdb;Port=5432;Database=PaymentDb;Username=Mohamed;Password=admin2023;"
    restart: always
    depends_on:
      - paymentdb

